In [1]:
import sqlite3

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\nehac\\Desktop\\SpringBoard_Work\\SQL Case Study - Country Club\\SQLFiles Tier 1'

In [4]:
#Q1: Some of the facilities charge a fee to members, but some do not.
#Write a SQL query to produce a list of the names of the facilities that do.


from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    

    query1 = """
        select * from Facilities where membercost != 0.0
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)

In [5]:
#Q2: How many facilities do not charge a fee to members?

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    


    query1 = """
        select count(name) as FreeFacilities from Facilities where membercost = 0.0
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(4,)

In [6]:
#/* Q3: Write an SQL query to show a list of facilities that charge a fee to members,
#where the fee is less than 20% of the facility's monthly maintenance cost.
#Return the facid, facility name, member cost, and monthly maintenance of the
#facilities in question. */


from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
select facid,name,membercost,monthlymaintenance from Facilities 
where (membercost > 0.0) and (membercost < (.2 * monthlymaintenance))

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 200)
(1, 'Tennis Court 2', 5, 200)
(4, 'Massage Room 1', 9.9, 3000)
(5, 'Massage Room 2', 9.9, 3000)
(6, 'Squash Court', 3.5, 80)

In [7]:
#/* Q4: Write an SQL query to retrieve the details of facilities with ID 1 and 5.
#Try writing the query without using the OR operator. */

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        select * from Facilities where facid in (1,5)
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)

In [8]:
#/* Q5: Produce a list of facilities, with each labelled as
#'cheap' or 'expensive', depending on if their monthly maintenance cost is
#more than $100. Return the name and monthly maintenance of the facilities
#in question. */

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
      select name,monthlymaintenance,
     case when monthlymaintenance > 100 Then 'expensive'
     when monthlymaintenance < 100 Then 'cheap'
    end as Facility
    from Facilities
    order by name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 50, 'cheap')
('Massage Room 1', 3000, 'expensive')
('Massage Room 2', 3000, 'expensive')
('Pool Table', 15, 'cheap')
('Snooker Table', 15, 'cheap')
('Squash Court', 80, 'cheap')
('Table Tennis', 10, 'cheap')
('Tennis Court 1', 200, 'expensive')
('Tennis Court 2', 200, 'expensive')

In [9]:
#/* Q6: You'd like to get the first and last name of the last member(s)
#who signed up. Try not to use the LIMIT clause for your solution. */

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        select firstname,surname,joindate from Members where joindate in (select Max(joindate) from Members)
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Darren', 'Smith', '2012-09-26 18:08:45')

In [10]:
#/* Q7: Produce a list of all members who have used a tennis court.
#Include in your output the name of the court, and the name of the member
#formatted as a single column. Ensure no duplicate data, and order by
#the member name. */


from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT DISTINCT f.name,m.firstname || ' ' || m.surname as name
FROM((Bookings as b
INNER JOIN Facilities as f
ON b.facid = f.facid)
INNER JOIN Members as m
ON b.memid = m.memid)     
WHERE f.name like 'Tennis%'
order by name"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', 'Anne Baker')
('Tennis Court 2', 'Anne Baker')
('Tennis Court 2', 'Burton Tracy')
('Tennis Court 1', 'Burton Tracy')
('Tennis Court 1', 'Charles Owen')
('Tennis Court 2', 'Charles Owen')
('Tennis Court 2', 'Darren Smith')
('Tennis Court 1', 'David Farrell')
('Tennis Court 2', 'David Farrell')
('Tennis Court 2', 'David Jones')
('Tennis Court 1', 'David Jones')
('Tennis Court 1', 'David Pinker')
('Tennis Court 1', 'Douglas Jones')
('Tennis Court 1', 'Erica Crumpet')
('Tennis Court 2', 'Florence Bader')
('Tennis Court 1', 'Florence Bader')
('Tennis Court 2', 'GUEST GUEST')
('Tennis Court 1', 'GUEST GUEST')
('Tennis Court 1', 'Gerald Butters')
('Tennis Court 2', 'Gerald Butters')
('Tennis Court 2', 'Henrietta Rumney')
('Tennis Court 1', 'Jack Smith')
('Tennis Court 2', 'Jack Smith')
('Tennis Court 1', 'Janice Joplette')
('Tennis Court 2', 'Janice Joplette')
('Tennis Court 2', 'Jemima Farrell')
('Tennis Court 1', 'Jemima Farrell')
('Tennis Court 1', 'Joan Coplin')
('Tennis Court 1', 'John Hunt')
('Tennis Court 2', 'John Hunt')
('Tennis Court 1', 'Matthew Genting')
('Tennis Court 2', 'Millicent Purview')
('Tennis Court 2', 'Nancy Dare')
('Tennis Court 1', 'Nancy Dare')
('Tennis Court 2', 'Ponder Stibbons')
('Tennis Court 1', 'Ponder Stibbons')
('Tennis Court 2', 'Ramnaresh Sarwin')
('Tennis Court 1', 'Ramnaresh Sarwin')
('Tennis Court 2', 'Tim Boothe')
('Tennis Court 1', 'Tim Boothe')
('Tennis Court 2', 'Tim Rownam')
('Tennis Court 1', 'Tim Rownam')
('Tennis Court 2', 'Timothy Baker')
('Tennis Court 1', 'Timothy Baker')
('Tennis Court 1', 'Tracy Smith')
('Tennis Court 2', 'Tracy Smith')

In [11]:
#/* Q8: Produce a list of bookings on the day of 2012-09-14 which
#will cost the member (or guest) more than $30. Remember that guests have
#different costs to members (the listed costs are per half-hour 'slot'), and
#the guest user's ID is always 0. Include in your output the name of the
#facility, the name of the member formatted as a single column, and the cost.
#Order by descending cost, and do not use any subqueries. */
#from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT m.firstname || ' ' || m.surname as MemberName,f.name as FacilityName,
        slots * (case when b.memid = 0 Then f.guestcost
         else f.membercost end) as Cost
        FROM Facilities as f
        INNER JOIN Bookings AS b
        ON f.facid = b.facid
        INNER JOIN Members as m
        ON m.memid = b.memid
        WHERE date(b.starttime) ='2012-09-14' 
        and (slots * (case when b.memid = 0 Then f.guestcost
        else f.membercost end) > 30)
        order by Cost desc
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST GUEST', 'Massage Room 2', 320)
('GUEST GUEST', 'Massage Room 1', 160)
('GUEST GUEST', 'Massage Room 1', 160)
('GUEST GUEST', 'Massage Room 1', 160)
('GUEST GUEST', 'Tennis Court 2', 150)
('GUEST GUEST', 'Tennis Court 1', 75)
('GUEST GUEST', 'Tennis Court 1', 75)
('GUEST GUEST', 'Tennis Court 2', 75)
('GUEST GUEST', 'Squash Court', 70.0)
('Jemima Farrell', 'Massage Room 1', 39.6)
('GUEST GUEST', 'Squash Court', 35.0)
('GUEST GUEST', 'Squash Court', 35.0)

In [12]:
#/* Q9: This time, produce the same result as in Q8, but using a subquery. */

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    Select MemberName, Facility from (        
    Select  m.firstname || ' ' || m.surname as MemberName ,f.name as Facility,
        b.slots * (CASE
                    WHEN m.memid = 0 THEN f.guestcost
                    ELSE f.membercost END) AS cost
      FROM Members AS m
      INNER JOIN Bookings AS b
      ON m.memid = b.memid
      INNER JOIN Facilities AS f
      ON b.facid = f.facid
      WHERE date(b.starttime) = '2012-09-14') as bookings_on_20120904
      where cost > 30
      order by cost desc

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST GUEST', 'Massage Room 2')
('GUEST GUEST', 'Massage Room 1')
('GUEST GUEST', 'Massage Room 1')
('GUEST GUEST', 'Massage Room 1')
('GUEST GUEST', 'Tennis Court 2')
('GUEST GUEST', 'Tennis Court 1')
('GUEST GUEST', 'Tennis Court 1')
('GUEST GUEST', 'Tennis Court 2')
('GUEST GUEST', 'Squash Court')
('Jemima Farrell', 'Massage Room 1')
('GUEST GUEST', 'Squash Court')
('GUEST GUEST', 'Squash Court')

In [13]:
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        WITH agg AS (
        select
        m.firstname, m.surname as member,
        f.name as facility,
        b.slots * (CASE
                    WHEN m.memid = 0 THEN f.guestcost
                    ELSE f.membercost END) AS cost
      FROM Members AS m
      INNER JOIN Bookings AS b
      ON m.memid = b.memid
      INNER JOIN Facilities AS f
      ON b.facid = f.facid
      WHERE date(b.starttime) = '2012-09-14') SELECT member, facility, cost FROM agg WHERE cost > 30
      order by cost desc
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST', 'Massage Room 2', 320)
('GUEST', 'Massage Room 1', 160)
('GUEST', 'Massage Room 1', 160)
('GUEST', 'Massage Room 1', 160)
('GUEST', 'Tennis Court 2', 150)
('GUEST', 'Tennis Court 1', 75)
('GUEST', 'Tennis Court 1', 75)
('GUEST', 'Tennis Court 2', 75)
('GUEST', 'Squash Court', 70.0)
('Farrell', 'Massage Room 1', 39.6)
('GUEST', 'Squash Court', 35.0)
('GUEST', 'Squash Court', 35.0)

In [14]:
# Q10: Produce a list of facilities with a total revenue less than 1000.
#The output of facility name and total revenue, sorted by revenue. Remember
#that there's a different cost for guests and members! 

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """select name, revenue_total 
    from (select name, 
          sum(case when memid = 0 then slots * guestcost 
          else slots * membercost end) as revenue_total
          from Bookings
          inner join Facilities
        using(facid)
        group by name)
    as Facilities_less_than_1000 where revenue_total < 1000
    order by revenue_total;"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [15]:
#/* Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order */

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT DISTINCT m.memid as MemberID,m.surname as Lastname,m.firstname as Name,
        m1.firstname,m1.surname as Recommender,m.recommendedby as RecommenderID
        FROM Members AS m
        INNER JOIN Members AS m1 ON (m1.memid = m.recommendedby)
        ORDER BY m.surname, m.firstname

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(15, 'Bader', 'Florence', 'Ponder', 'Stibbons', '9')
(12, 'Baker', 'Anne', 'Ponder', 'Stibbons', '9')
(16, 'Baker', 'Timothy', 'Jemima', 'Farrell', '13')
(8, 'Boothe', 'Tim', 'Tim', 'Rownam', '3')
(5, 'Butters', 'Gerald', 'Darren', 'Smith', '1')
(22, 'Coplin', 'Joan', 'Timothy', 'Baker', '16')
(36, 'Crumpet', 'Erica', 'Tracy', 'Smith', '2')
(7, 'Dare', 'Nancy', 'Janice', 'Joplette', '4')
(20, 'Genting', 'Matthew', 'Gerald', 'Butters', '5')
(35, 'Hunt', 'John', 'Millicent', 'Purview', '30')
(11, 'Jones', 'David', 'Janice', 'Joplette', '4')
(26, 'Jones', 'Douglas', 'David', 'Jones', '11')
(4, 'Joplette', 'Janice', 'Darren', 'Smith', '1')
(21, 'Mackenzie', 'Anna', 'Darren', 'Smith', '1')
(10, 'Owen', 'Charles', 'Darren', 'Smith', '1')
(17, 'Pinker', 'David', 'Jemima', 'Farrell', '13')
(30, 'Purview', 'Millicent', 'Tracy', 'Smith', '2')
(27, 'Rumney', 'Henrietta', 'Matthew', 'Genting', '20')
(24, 'Sarwin', 'Ramnaresh', 'Florence', 'Bader', '15')
(14, 'Smith', 'Jack', 'Darren', 'Smith', '1')
(9, 'Stibbons', 'Ponder', 'Burton', 'Tracy', '6')
(29, 'Worthington-Smyth', 'Henry', 'Tracy', 'Smith', '2')

In [16]:
#/* Q13: Find the facilities usage by month, but not guests */

from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
   
    query1 = """SELECT name,facid, SUM(slots) FROM Bookings
inner join Facilities
using(facid)
GROUP BY facid 
ORDER BY facid"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', 0, 1320)
('Tennis Court 2', 1, 1278)
('Badminton Court', 2, 1209)
('Table Tennis', 3, 830)
('Massage Room 1', 4, 1404)
('Massage Room 2', 5, 228)
('Squash Court', 6, 1104)
('Snooker Table', 7, 908)
('Pool Table', 8, 910)

In [17]:
 #/* Q12: Find the facilities with their usage by member, but not guests */ 
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
  
    query1 = """SELECT facid as FacID,name as FacilityName,SUM(slots) as JulyUsage 
                FROM Bookings
                inner join Facilities
                using(facid)
                WHERE (Extract(month from '2017-07-01') = 7)
                GROUP BY facid"""
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks

OperationalError: near "from": syntax error